### ISSUE TITLE
有些汉字字母排序无法识别

### ISSUE THREAD

**Issue by LayChan** [ijinfeng/IASearchKit#1]
作者你好，这个库很棒，但有些排序无法识别，具体看截图，可能还会存在其他情况
![Simulator Screen Shot - iPhone Xs Max - 2019-05-02 at 14 17 45](https://user-images.githubusercontent.com/15124524/57059029-d1855e80-6ce5-11e9-9d2d-a4637c724cce.png)
![Simulator Screen Shot - iPhone Xs Max - 2019-05-02 at 14 17 14](https://user-images.githubusercontent.com/15124524/57059031-d1855e80-6ce5-11e9-87e4-347b148bd254.png)

**Comment by steven326** [comment]
同问，作者最近有计划解决这个问题吗

**Comment by ijinfeng** [comment]
这个问题已修复，请下载新版本使用。
`pod 'IASearchKit', '~> 1.2.0'`
